FROM golang:1.22-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN GOOS=linux GOARCH=amd64 go build -o bootstrap main.go

FROM amazon/aws-lambda-go:1

COPY --from=builder /app/bootstrap .

CMD ["bootstrap"]